# Include this file from kitty.conf to apply the NSD desktop palette.
font_family DejaVu Sans Mono
font_size 10.0
window_padding_width 12
background #090D16
foreground #C6D3EA
cursor #00EB74
selection_background #C170FF
selection_foreground #090D16
background_opacity 1.0
color0 #090D16
color1 #FF567A
color2 #00EB74
color3 #FFB85C
color4 #5A96FF
color5 #C170FF
color6 #54DDEB
color7 #C6D3EA
color8 #52617A
color9 #FF87A0
color10 #76FFA9
color11 #FFD390
color12 #91B9FF
color13 #DAA8FF
color14 #9AEFF7
color15 #F0F4FF
